<?php
    $config['Browsers'] = array (
		// Common web browsers text (IE and Netscape must not be in this list)
		'icab' 			=> 'iCab',
		'go!zilla' 		=> 'Go!Zilla',
		'konqueror'		=> 'Konqueror',
		'links' 		=> 'Links',
		'lynx' 			=> 'Lynx',
		'omniweb' 		=> 'OmniWeb',
		'opera' 		=> 'Opera',
		'msie 6\.0' 	=> 'Microsoft Internet Explorer 6.0',
		'apachebench' 	=> 'ApacheBench',
		'wget' 			=> 'Wget',
		'22acidownload' => '22AciDownload',
		'aol\\-iweng' 	=> 'AOL-Iweng',
		'amaya' 		=> 'Amaya',
		'amigavoyager' 	=> 'AmigaVoyager',
		'aweb' 			=> 'AWeb',
		'bpftp' 		=> 'BPFTP',
		'chimera' 		=> 'Chimera',
		'cyberdog' 		=> 'Cyberdog',
		'dillo' 		=> 'Dillo',
		'dreamcast' 	=> 'Dreamcast',
		'downloadagent' => 'DownloadAgent',
		'ecatch' 		=> 'eCatch',
		'emailsiphon' 	=> 'EmailSiphon',
		'encompass'		=> 'Encompass',
		'friendlyspider' => 'FriendlySpider',
		'fresco' 		=> 'ANT Fresco',
		'galeon'		=> 'Galeon',
		'getright' 		=> 'GetRight',
		'headdump' 		=> 'HeadDump',
		'hotjava' 		=> 'Sun HotJava',
		'ibrowse' 		=> 'IBrowse',
		'intergo' 		=> 'InterGO',
		'k-meleon' 		=> 'K-Meleon',
		'linemodebrowser' => 'W3C Line Mode Browser',
		'lotus-notes' 	=> 'Lotus Notes web client',
		'macweb' 		=> 'MacWeb',
		'multizilla' 	=> 'MultiZilla',
		'ncsa_mosaic' 	=> 'NCSA Mosaic',
		'netpositive' 	=> 'NetPositive',
		'nutscrape' 	=> 'Nutscrape',
		'msfrontpageexpress' => 'MS FrontPage Express',
		'phoenix' 		=> 'Phoenix',
		'firebird' 		=> 'Mozilla Firebird',
		'firefox' 		=> 'Mozilla Firefox',
		'safari' 		=> 'Safari',
		'tzgeturl' 		=> 'TzGetURL',
		'viking' 		=> 'Viking',
		'webfetcher' 	=> 'WebFetcher',
		'webexplorer' 	=> 'IBM-WebExplorer',
		'webmirror' 	=> 'WebMirror',
		'webvcr' 		=> 'WebVCR',
		// Site grabbers
		'teleport' 		=> 'TelePort Pro',
		'webcapture' 	=> 'Acrobat',
		'webcopier' 	=> 'WebCopier',
		// Music only browsers
		'real' 			=> 'RealAudio or compatible (media player)',
		'winamp' 		=> 'WinAmp (media player)',				// Works for winampmpeg and winamp3httprdr
		'windows-media-player' => 'Windows Media Player (media player)',
		'audion' 		=> 'Audion (media player)',
		'freeamp' 		=> 'FreeAmp (media player)',
		'itunes' 		=> 'Apple iTunes (media player)',
		'jetaudio' 		=> 'JetAudio (media player)',
		'mint_audio' 	=> 'Mint Audio (media player)',
		'mpg123' 		=> 'mpg123 (media player)',
		'nsplayer' 		=> 'NetShow Player (media player)',
		'sonique' 		=> 'Sonique (media player)',
		'uplayer' 		=> 'Ultra Player (media player)',
		'xmms' 			=> 'XMMS (media player)',
		'xaudio' 		=> 'Some XAudio Engine based MPEG player (media player)',
		// PDA/Phonecell browsers
		'alcatel' 		=> 'Alcatel Browser (PDA/Phone browser)',
		'ericsson' 		=> 'Ericsson Browser (PDA/Phone browser)',
		'mot-' 			=> 'Motorola Browser (PDA/Phone browser)',
		'nokia' 		=> 'Nokia Browser (PDA/Phone browser)',
		'panasonic' 	=> 'Panasonic Browser (PDA/Phone browser)',
		'philips' 		=> 'Philips Browser (PDA/Phone browser)',
		'sonyericsson' 	=> 'Sony/Ericsson Browser (PDA/Phone browser)',
		'mmef' 			=> 'Microsoft Mobile Explorer (PDA/Phone browser)',
		'mspie' 		=> 'MS Pocket Internet Explorer (PDA/Phone browser)',
		'wapalizer' 	=> 'WAPalizer (PDA/Phone browser)',
		'wapsilon' 		=> 'WAPsilon (PDA/Phone browser)',
		'webcollage' 	=> 'WebCollage (PDA/Phone browser)',
		'up\.' 			=> 'UP.Browser (PDA/Phone browser)',					// Works for UP.Browser and UP.Link
		// PDA/Phonecell I-Mode browsers
		'docomo' 		=> 'I-Mode phone (PDA/Phone browser)',
		'portalmmm' 	=> 'I-Mode phone (PDA/Phone browser)',
		// Others (TV)
		'webtv' 		=> 'WebTV browser',
		// Other kind of browsers
		'csscheck' 		=> 'WDG CSS Validator',
		'w3m' 			=> 'w3m',
		'w3c_css_validator' => 'W3C CSS Validator',
		'w3c_validator' => 'W3C HTML Validator',
		'wdg_validator' => 'WDG HTML Validator',
		'webzip' 		=> 'WebZIP',
		'staroffice' 	=> 'StarOffice',
		'mozilla' 		=> 'Mozilla',
		'libwww' 		=> 'LibWWW',
	);
?>