<?php
class R4c8f8765d5d84763b04108486318cd70 extends CakeRelease {

/**
 * Migration description
 *
 * @var string
 * @access public
 */
	public $description = 'Migration for Management version 0.8';

/**
 * Plugin name
 *
 * @var string
 * @access public
 */
	public $plugin = 'Management';

/**
 * Actions to be performed
 *
 * @var array $migration
 * @access public
 */
	public $migration = array(
		'up' => array(
			'create_table' => array(
				'addresses' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'street' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'city' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'province' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'postal' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 10, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'country_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'continent_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'plugin' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'foreign_key' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'backups' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'plugin' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'model' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'last_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'data' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'configs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'key' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'key' => 'unique', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'value' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'type' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 20, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'options' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'core' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'config_key' => array('column' => 'key', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'groups' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'description' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'parent_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'index'),
					'lft' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'rght' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'parent_id' => array('column' => 'parent_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'ip_addresses' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'ip_address' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'user_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'description' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'times_blocked' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 6),
					'unlock_at' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'risk' => array('type' => 'integer', 'null' => false, 'default' => '1'),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '1'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'logs' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'title' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'model' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'model_id' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'action' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'user_id' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'change' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'version_id' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'menu_items' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 200, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'slug' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 200, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'link' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'prefix' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'plugin' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'controller' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'action' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'params' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'force_backend' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'force_frontend' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'class' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'menu_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'index'),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'index'),
					'parent_id' => array('type' => 'integer', 'null' => true, 'default' => '0'),
					'lft' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'rght' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'menuItems_groupIndex' => array('column' => 'group_id', 'unique' => 0),
						'menuItems_menuIndex' => array('column' => 'menu_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'menus' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'type' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'item_count' => array('type' => 'integer', 'null' => false, 'default' => '0'),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'menu_index' => array('column' => array('type', 'active'), 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'module_positions' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'modules' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'key' => 'unique', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'content' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'plugin' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'module' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'config' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'theme_id' => array('type' => 'integer', 'null' => false, 'default' => '0'),
					'position_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => '0'),
					'ordering' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'admin' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'locked' => array('type' => 'boolean', 'null' => false, 'default' => NULL),
					'locked_by' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'locked_since' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'show_heading' => array('type' => 'boolean', 'null' => false, 'default' => '1'),
					'core' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'author' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'licence' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 75, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'url' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'update_url' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'name' => array('column' => 'name', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'modules_routes' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'module_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'route_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'relations' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'description' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'plugin' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'model' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'key' => 'unique', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'foreign_key' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'conditions' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'fields' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'order' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'dependent' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'limit' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'offset' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'counter_cache' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'counter_scope' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'join_table' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 150, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'with' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 150, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'association_foreign_key' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'unique' => array('type' => 'boolean', 'null' => true, 'default' => '0'),
					'finder_query' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'delete_query' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'insert_query' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'bind' => array('type' => 'boolean', 'null' => false, 'default' => '1'),
					'reverse_association' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'type_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'class_name' => array('column' => 'model', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'routes' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'primary'),
					'core' => array('type' => 'boolean', 'null' => false, 'default' => NULL),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'url' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'prefix' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'plugin' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'controller' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'action' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'values' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'pass' => array('type' => 'string', 'null' => true, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'rules' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'force_backend' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'force_frontend' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'order_id' => array('type' => 'integer', 'null' => false, 'default' => '1'),
					'ordering' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'theme_id' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => NULL),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'short_urls' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'primary'),
					'url' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'themes' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'description' => array('type' => 'text', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'author' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 150, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'url' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'update_url' => array('type' => 'string', 'null' => true, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'licence' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'core' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'trash' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'primary'),
					'model' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'foreign_key' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 36, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'data' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'latin1_swedish_ci', 'charset' => 'latin1'),
					'deleted' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'deleted_by' => array('type' => 'integer', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'latin1', 'collate' => 'latin1_swedish_ci', 'engine' => 'MyISAM'),
				),
				'relation_types' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'length' => 10, 'key' => 'primary'),
					'name' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'type' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'key' => 'unique', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'description' => array('type' => 'text', 'null' => false, 'default' => NULL, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'created' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'type' => array('column' => 'type', 'unique' => 1),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
				'users' => array(
					'id' => array('type' => 'integer', 'null' => false, 'default' => NULL, 'key' => 'primary'),
					'username' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 20, 'key' => 'index', 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'email' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'password' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 40, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'birthday' => array('type' => 'date', 'null' => true, 'default' => NULL),
					'active' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'group_id' => array('type' => 'integer', 'null' => false, 'default' => NULL),
					'ip_address' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'browser' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 100, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'operating_system' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 50, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'last_login' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'last_click' => array('type' => 'datetime', 'null' => true, 'default' => NULL),
					'country' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 150, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'city' => array('type' => 'string', 'null' => false, 'default' => NULL, 'length' => 150, 'collate' => 'utf8_general_ci', 'charset' => 'utf8'),
					'is_mobile' => array('type' => 'boolean', 'null' => false, 'default' => '0'),
					'created' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'modified' => array('type' => 'datetime', 'null' => false, 'default' => NULL),
					'facebook_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20),
					'twitter_id' => array('type' => 'integer', 'null' => false, 'default' => '0', 'length' => 20, 'key' => 'index'),
					'indexes' => array(
						'PRIMARY' => array('column' => 'id', 'unique' => 1),
						'username' => array('column' => array('username', 'email'), 'unique' => 1),
						'twitter_id' => array('column' => 'twitter_id', 'unique' => 0),
					),
					'tableParameters' => array('charset' => 'utf8', 'collate' => 'utf8_general_ci', 'engine' => 'InnoDB'),
				),
			),
		),
		'down' => array(
			'drop_table' => array(
				'addresses', 'backups', 'configs', 'groups', 'ip_addresses', 'logs', 'menu_items', 'menus', 'module_positions', 'modules', 'modules_routes', 'relations', 'routes', 'short_urls', 'themes', 'trash', 'types', 'users'
			),
		),
	);

/**
 * Fixtures for data
 *
 * @var array $fixtures
 * @access public
 */
	public $fixtures = array(
	'core' => array(
		'Group' => array(
			array(
				'id' => 1,
				'name' => 'Administrators',
				'description' => 'Site Administrators',
				'created' => '2010-02-04 16:53:33',
				'modified' => '2010-02-04 16:53:33',
				'parent_id' => 0,
				'lft' => 1,
				'rght' => 2
			),
			array(
				'id' => 2,
				'name' => 'Users',
				'description' => '',
				'created' => '2010-02-17 23:14:32',
				'modified' => '2010-02-17 23:14:32',
				'parent_id' => 0,
				'lft' => 3,
				'rght' => 4
			),
		),
		'Log' => array(
			array(
				'id' => 13,
				'title' => 'Stats',
				'description' => 'MenuItem \"Stats\" (91) updated by Management.User \"1\" (1).',
				'model' => 'MenuItem',
				'model_id' => 91,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'parent_id (58) => (1)',
				'version_id' => NULL,
				'created' => '2010-04-17 01:29:18'
			),
			array(
				'id' => 12,
				'title' => 'Categories',
				'description' => 'MenuItem \"Categories\" (95) updated by Management.User \"1\" (1).',
				'model' => 'MenuItem',
				'model_id' => 95,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'parent_id (1) => (5), force_backend (0) => (1)',
				'version_id' => NULL,
				'created' => '2010-04-17 01:26:59'
			),
			array(
				'id' => 11,
				'title' => 'Config (73)',
				'description' => 'Config (73) updated by Management.User \"1\" (1).',
				'model' => 'Config',
				'model_id' => 73,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'value (false) => (true)',
				'version_id' => NULL,
				'created' => '2010-04-17 01:00:06'
			),
			array(
				'id' => 10,
				'title' => 'Config (73)',
				'description' => 'Config (73) updated by Management.User \"1\" (1).',
				'model' => 'Config',
				'model_id' => 73,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'value (true) => (false)',
				'version_id' => NULL,
				'created' => '2010-04-17 00:37:28'
			),
			array(
				'id' => 9,
				'title' => 'Config (73)',
				'description' => 'Config (73) updated by Management.User \"1\" (1).',
				'model' => 'Config',
				'model_id' => 73,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'value (false) => (true)',
				'version_id' => NULL,
				'created' => '2010-04-17 00:36:59'
			),
			array(
				'id' => 8,
				'title' => 'Config (73)',
				'description' => 'Config (73) updated by Management.User \"1\" (1).',
				'model' => 'Config',
				'model_id' => 73,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'value (true) => (false)',
				'version_id' => NULL,
				'created' => '2010-04-17 00:30:49'
			),
			array(
				'id' => 7,
				'title' => 'Config (73)',
				'description' => 'Config (73) updated by Management.User \"1\" (1).',
				'model' => 'Config',
				'model_id' => 73,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'value (false) => (true)',
				'version_id' => NULL,
				'created' => '2010-04-17 00:28:33'
			),
			array(
				'id' => 6,
				'title' => 'Config (73)',
				'description' => 'Config (73) updated by Management.User \"1\" (1).',
				'model' => 'Config',
				'model_id' => 73,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'value (true) => (false)',
				'version_id' => NULL,
				'created' => '2010-04-17 00:27:10'
			),
			array(
				'id' => 5,
				'title' => 'Config (73)',
				'description' => 'Config (73) added by Management.User \"1\" (1).',
				'model' => 'Config',
				'model_id' => 73,
				'action' => 'add',
				'user_id' => 1,
				'change' => 'key () => (Cms.allow_ratings), value () => (true), type () => (bool), options () => (true,false), core () => (0), description () => (<p>\r\n	If you would like to not allow rating of items, set this value to false. Default is true.</p>\r\n)',
				'version_id' => NULL,
				'created' => '2010-04-17 00:25:11'
			),
			array(
				'id' => 3,
				'title' => 'Rating (2)',
				'description' => 'Rating (2) added by Management.User \"1\" (1).',
				'model' => 'Rating',
				'model_id' => 2,
				'action' => 'add',
				'user_id' => 1,
				'change' => 'class () => (Cms.Content), foreign_id () => (4), rating () => (4), user_id () => (1), ip () => (::1), created () => (2010-04-16 22:44:42)',
				'version_id' => NULL,
				'created' => '2010-04-16 22:44:42'
			),
			array(
				'id' => 4,
				'title' => 'Extending Infinitas',
				'description' => 'Content (4) updated by Management.User \"1\" (1).',
				'model' => 'Content',
				'model_id' => 4,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'rating () => (4.50)',
				'version_id' => NULL,
				'created' => '2010-04-16 22:44:42'
			),
			array(
				'id' => 1,
				'title' => 'Rating (1)',
				'description' => 'Rating (1) added by Management.User \"1\" (1).',
				'model' => 'Rating',
				'model_id' => 1,
				'action' => 'add',
				'user_id' => 1,
				'change' => 'class () => (Cms.Content), foreign_id () => (4), rating () => (5), user_id () => (1), ip () => (::1), created () => (2010-04-16 22:39:55)',
				'version_id' => NULL,
				'created' => '2010-04-16 22:39:55'
			),
			array(
				'id' => 2,
				'title' => 'Extending Infinitas',
				'description' => 'Content (4) updated by Management.User \"1\" (1).',
				'model' => 'Content',
				'model_id' => 4,
				'action' => 'edit',
				'user_id' => 1,
				'change' => 'rating () => (5.00)',
				'version_id' => NULL,
				'created' => '2010-04-16 22:39:55'
			),
		),
		'Menu' => array(
			array(
				'id' => 4,
				'name' => 'plugin_categories',
				'type' => 'plugin_categories',
				'item_count' => 0,
				'active' => 1,
				'created' => '2010-09-09 22:27:27',
				'modified' => '2010-09-09 22:27:27'
			),
		),
		'Module' => array(
			array(
				'id' => 25,
				'name' => 'Plugin Dock',
				'content' => '',
				'plugin' => 'menu',
				'module' => 'admin/dock',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 1,
				'group_id' => 1,
				'ordering' => 1,
				'admin' => 1,
				'active' => 1,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-09-09 19:47:53',
				'modified' => '2010-09-09 19:47:53'
			),
			array(
				'id' => 12,
				'name' => 'Admin Menu',
				'content' => '',
				'plugin' => 'menu',
				'module' => 'admin/menu',
				'config' => '{\"menu\":\"core_admin\"}',
				'theme_id' => 0,
				'position_id' => 1,
				'group_id' => 1,
				'ordering' => 2,
				'admin' => 1,
				'active' => 1,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-01-27 18:14:16',
				'modified' => '2010-09-09 19:09:31'
			),
			array(
				'id' => 26,
				'name' => 'Admin Todo List',
				'content' => '',
				'plugin' => 'menu',
				'module' => 'admin/todo',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 1,
				'group_id' => 1,
				'ordering' => 3,
				'admin' => 1,
				'active' => 1,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-09-10 15:40:06',
				'modified' => '2010-09-10 15:09:11'
			),
			array(
				'id' => 13,
				'name' => 'Frontend Menu',
				'content' => '',
				'plugin' => 'management',
				'module' => 'main_menu',
				'config' => '{\"public\":\"main_menu\",\"registered\":\"registered_users\"}',
				'theme_id' => 0,
				'position_id' => 1,
				'group_id' => 2,
				'ordering' => 4,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-02-01 00:57:01',
				'modified' => '2010-09-10 15:41:16'
			),
			array(
				'id' => 16,
				'name' => 'Google analytics',
				'content' => '',
				'plugin' => '',
				'module' => 'google_analytics',
				'config' => '{\"code\":\"UA-xxxxxxxx-x\"}',
				'theme_id' => 0,
				'position_id' => 2,
				'group_id' => 2,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-02-01 20:45:05',
				'modified' => '2010-02-17 23:44:56'
			),
			array(
				'id' => 9,
				'name' => 'Latest Tweets',
				'content' => '',
				'plugin' => '',
				'module' => 'twitter_tweets',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 3,
				'group_id' => 1,
				'ordering' => 2,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://www.infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-01-21 19:23:37',
				'modified' => '2010-01-21 20:46:54'
			),
			array(
				'id' => 19,
				'name' => 'Browse',
				'content' => '',
				'plugin' => 'shop',
				'module' => 'categories',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 3,
				'group_id' => 2,
				'ordering' => 2,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-05-03 17:50:09',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 7,
				'name' => 'Latest News',
				'content' => '',
				'plugin' => '',
				'module' => 'latest_news',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 3,
				'group_id' => 1,
				'ordering' => 3,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://www.i-project.co.za',
				'update_url' => '',
				'created' => '2010-01-19 11:40:45',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 4,
				'name' => 'Popular Posts',
				'content' => '',
				'plugin' => '',
				'module' => '',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 1,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://www.i-project.co.za',
				'update_url' => '',
				'created' => '2010-01-19 00:58:20',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 10,
				'name' => 'Twitter News',
				'content' => '',
				'plugin' => '',
				'module' => 'twitter_search',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 1,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://www.infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-01-21 19:50:17',
				'modified' => '2010-02-08 01:46:56'
			),
			array(
				'id' => 22,
				'name' => 'Your Cart',
				'content' => '',
				'plugin' => 'shop',
				'module' => 'cart',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 2,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-05-08 01:44:09',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 23,
				'name' => 'Your Wishlist',
				'content' => '',
				'plugin' => 'shop',
				'module' => 'wishlist',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 2,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-05-08 01:44:39',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 24,
				'name' => 'Rate This',
				'content' => '',
				'plugin' => 'management',
				'module' => 'rate',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 2,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org/',
				'update_url' => '',
				'created' => '2010-05-10 20:06:53',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 2,
				'name' => 'login',
				'content' => '',
				'plugin' => '',
				'module' => 'login',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 1,
				'ordering' => 2,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://www.i-project.co.za',
				'update_url' => '',
				'created' => '2010-01-19 00:30:53',
				'modified' => '2010-02-01 01:22:16'
			),
			array(
				'id' => 11,
				'name' => 'Infinitas Users',
				'content' => '<div style=\"padding-top:10px\"><script type=\"text/javascript\" src=\"http://www.ohloh.net/p/442724/widgets/project_users.js?style=blue\"></script></div>',
				'plugin' => '',
				'module' => '',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 1,
				'ordering' => 3,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-01-21 20:02:55',
				'modified' => '2010-02-08 01:59:04'
			),
			array(
				'id' => 14,
				'name' => 'Tag Cloud',
				'content' => '',
				'plugin' => 'blog',
				'module' => 'post_tag_cloud',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 2,
				'ordering' => 4,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-02-01 16:01:01',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 15,
				'name' => 'Post Dates',
				'content' => '',
				'plugin' => 'blog',
				'module' => 'post_dates',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 4,
				'group_id' => 2,
				'ordering' => 5,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 1,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-02-01 16:34:00',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 18,
				'name' => 'banners',
				'content' => '',
				'plugin' => '',
				'module' => 'banners',
				'config' => '{\"path\":\"/banners\"}',
				'theme_id' => 0,
				'position_id' => 5,
				'group_id' => 2,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-05-03 14:59:01',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 20,
				'name' => 'Promotion 1',
				'content' => '',
				'plugin' => 'shop',
				'module' => 'promotion_1',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 6,
				'group_id' => 2,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-05-07 19:17:15',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 21,
				'name' => 'Promotion 2',
				'content' => '',
				'plugin' => 'shop',
				'module' => 'promotion_2',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 6,
				'group_id' => 2,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => 'MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-05-07 19:18:13',
				'modified' => '2010-09-09 19:09:05'
			),
			array(
				'id' => 27,
				'name' => 'Admin Dashboard Icons',
				'content' => '',
				'plugin' => 'menu',
				'module' => 'admin/dashboard_icons',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 8,
				'group_id' => 1,
				'ordering' => 1,
				'admin' => 1,
				'active' => 1,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => '&copy; MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-09-11 17:32:33',
				'modified' => '2010-09-11 17:35:48'
			),
			array(
				'id' => 29,
				'name' => 'Overall Stats',
				'content' => '',
				'plugin' => 'view_counter',
				'module' => 'admin/overall',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 8,
				'group_id' => 1,
				'ordering' => 2,
				'admin' => 1,
				'active' => 1,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => '&copy; MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-09-12 21:45:32',
				'modified' => '2010-09-12 21:50:46'
			),
			array(
				'id' => 28,
				'name' => 'View Counter Stats',
				'content' => '',
				'plugin' => 'view_counter',
				'module' => 'admin/popular_items',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 8,
				'group_id' => 1,
				'ordering' => 3,
				'admin' => 1,
				'active' => 1,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 0,
				'author' => 'Infinitas',
				'licence' => '&copy; MIT',
				'url' => 'http://infinitas-cms.org',
				'update_url' => '',
				'created' => '2010-09-11 18:00:14',
				'modified' => '2010-09-12 21:51:02'
			),
			array(
				'id' => 5,
				'name' => 'search',
				'content' => '',
				'plugin' => '',
				'module' => 'search',
				'config' => '',
				'theme_id' => 0,
				'position_id' => 12,
				'group_id' => 1,
				'ordering' => 1,
				'admin' => 0,
				'active' => 0,
				'locked' => 0,
				'locked_by' => 0,
				'locked_since' => 0,
				'show_heading' => 0,
				'core' => 1,
				'author' => 'Infinitas',
				'licence' => '',
				'url' => 'http://www.i-project.co.za',
				'update_url' => '',
				'created' => '2010-01-19 11:22:09',
				'modified' => '2010-01-19 14:44:49'
			),
		),
		'ModulesRoute' => array(
			array(
				'id' => 13,
				'module_id' => 7,
				'route_id' => 0
			),
			array(
				'id' => 17,
				'module_id' => 5,
				'route_id' => 0
			),
			array(
				'id' => 21,
				'module_id' => 9,
				'route_id' => 7
			),
			array(
				'id' => 25,
				'module_id' => 2,
				'route_id' => 7
			),
			array(
				'id' => 26,
				'module_id' => 2,
				'route_id' => 8
			),
			array(
				'id' => 27,
				'module_id' => 2,
				'route_id' => 9
			),
			array(
				'id' => 28,
				'module_id' => 10,
				'route_id' => 0
			),
			array(
				'id' => 40,
				'module_id' => 14,
				'route_id' => 0
			),
			array(
				'id' => 41,
				'module_id' => 15,
				'route_id' => 0
			),
			array(
				'id' => 47,
				'module_id' => 20,
				'route_id' => 0
			),
			array(
				'id' => 48,
				'module_id' => 21,
				'route_id' => 0
			),
			array(
				'id' => 49,
				'module_id' => 22,
				'route_id' => 0
			),
			array(
				'id' => 50,
				'module_id' => 23,
				'route_id' => 0
			),
			array(
				'id' => 53,
				'module_id' => 24,
				'route_id' => 19
			),
			array(
				'id' => 54,
				'module_id' => 24,
				'route_id' => 22
			),
			array(
				'id' => 55,
				'module_id' => 24,
				'route_id' => 26
			),
			array(
				'id' => 56,
				'module_id' => 4,
				'route_id' => 0
			),
			array(
				'id' => 60,
				'module_id' => 13,
				'route_id' => 0
			),
			array(
				'id' => 61,
				'module_id' => 18,
				'route_id' => 0
			),
			array(
				'id' => 62,
				'module_id' => 19,
				'route_id' => 0
			),
			array(
				'id' => 65,
				'module_id' => 25,
				'route_id' => 0
			),
			array(
				'id' => 66,
				'module_id' => 12,
				'route_id' => 0
			),
			array(
				'id' => 67,
				'module_id' => 26,
				'route_id' => 0
			),
			array(
				'id' => 69,
				'module_id' => 27,
				'route_id' => 9
			),
			array(
				'id' => 71,
				'module_id' => 28,
				'route_id' => 9
			),
			array(
				'id' => 72,
				'module_id' => 29,
				'route_id' => 9
			),
		),
		'ModulePosition' => array(
			array(
				'id' => 1,
				'name' => 'top',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 2,
				'name' => 'bottom',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 3,
				'name' => 'left',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 4,
				'name' => 'right',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 5,
				'name' => 'custom1',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 6,
				'name' => 'custom2',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 7,
				'name' => 'custom3',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 8,
				'name' => 'custom4',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 9,
				'name' => 'bread_crumbs',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 10,
				'name' => 'debug',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 11,
				'name' => 'feeds',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 12,
				'name' => 'search',
				'created' => '2010-01-18 21:45:23',
				'modified' => '2010-01-18 21:45:23'
			),
			array(
				'id' => 13,
				'name' => 'hidden',
				'created' => '2010-03-05 18:33:20',
				'modified' => '2010-03-05 18:33:20'
			),
		),
		'Route' => array(
			array(
				'id' => 7,
				'core' => 0,
				'name' => 'Home Page',
				'url' => '/',
				'prefix' => '',
				'plugin' => 'cms',
				'controller' => 'frontpages',
				'action' => '',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 0,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 2,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 16:50:39',
				'modified' => '2010-01-20 17:45:43'
			),
			array(
				'id' => 8,
				'core' => 0,
				'name' => 'Pages',
				'url' => '/pages/*',
				'prefix' => '',
				'plugin' => '0',
				'controller' => 'pages',
				'action' => 'display',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 0,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 3,
				'theme_id' => 4,
				'active' => 1,
				'created' => '2010-01-13 18:26:36',
				'modified' => '2010-01-14 00:38:53'
			),
			array(
				'id' => 9,
				'core' => 0,
				'name' => 'Admin Home',
				'url' => '/admin',
				'prefix' => 'admin',
				'plugin' => 'management',
				'controller' => 'management',
				'action' => 'dashboard',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 1,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 4,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 18:36:50',
				'modified' => '2010-01-13 18:36:50'
			),
			array(
				'id' => 11,
				'core' => 0,
				'name' => 'Management Home',
				'url' => '/admin/management',
				'prefix' => 'admin',
				'plugin' => 'management',
				'controller' => 'management',
				'action' => 'dashboard',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 1,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 6,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 18:40:23',
				'modified' => '2010-01-13 18:42:53'
			),
			array(
				'id' => 12,
				'core' => 0,
				'name' => 'Blog Home - Backend',
				'url' => '/admin/blog',
				'prefix' => 'admin',
				'plugin' => 'blog',
				'controller' => 'posts',
				'action' => 'dashboard',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 1,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 7,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 18:45:23',
				'modified' => '2010-01-13 19:02:17'
			),
			array(
				'id' => 13,
				'core' => 0,
				'name' => 'Blog Home - Frontend',
				'url' => '/blog',
				'prefix' => '',
				'plugin' => 'blog',
				'controller' => 'posts',
				'action' => '',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 8,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 18:47:07',
				'modified' => '2010-01-13 19:10:00'
			),
			array(
				'id' => 14,
				'core' => 0,
				'name' => 'Cms Home - Backend',
				'url' => '/admin/cms',
				'prefix' => 'admin',
				'plugin' => 'cms',
				'controller' => 'categories',
				'action' => 'dashboard',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 1,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 9,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 19:01:14',
				'modified' => '2010-01-13 19:04:59'
			),
			array(
				'id' => 15,
				'core' => 0,
				'name' => 'Cms Home - Frontend',
				'url' => '/cms',
				'prefix' => '',
				'plugin' => 'cms',
				'controller' => 'frontpages',
				'action' => '',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 10,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 19:05:28',
				'modified' => '2010-01-18 01:40:23'
			),
			array(
				'id' => 19,
				'core' => 0,
				'name' => 'Cms SEO',
				'url' => '/cms/:category/:id-:slug',
				'prefix' => '',
				'plugin' => 'cms',
				'controller' => 'contents',
				'action' => 'view',
				'values' => '',
				'pass' => 'id,slug',
				'rules' => '{\"id\":\"[0-9]+\"}',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 11,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-18 01:35:21',
				'modified' => '2010-01-18 02:09:17'
			),
			array(
				'id' => 16,
				'core' => 0,
				'name' => 'Newsletter Home - Backend',
				'url' => '/admin/newsletter',
				'prefix' => 'admin',
				'plugin' => 'newsletter',
				'controller' => 'newsletters',
				'action' => 'dashboard',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 1,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 12,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-01-13 19:18:16',
				'modified' => '2010-01-18 01:35:56'
			),
			array(
				'id' => 18,
				'core' => 0,
				'name' => 'Blog Test',
				'url' => '/p/:year/:month/:day',
				'prefix' => '',
				'plugin' => 'blog',
				'controller' => 'posts',
				'action' => '',
				'values' => 'day:null',
				'pass' => '',
				'rules' => '{\"year\":\"[12][0-9]{3}\",\r\n\"month\":\"0[1-9]|1[012]\",\r\n\"day\":\"0[1-9]|[12][0-9]|3[01]\"}\r\n',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 13,
				'theme_id' => 1,
				'active' => 1,
				'created' => '2010-01-13 19:36:31',
				'modified' => '2010-01-18 01:35:41'
			),
			array(
				'id' => 20,
				'core' => 0,
				'name' => 'Login',
				'url' => '/login',
				'prefix' => '',
				'plugin' => 'management',
				'controller' => 'users',
				'action' => 'login',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 0,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 14,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-02-04 21:05:36',
				'modified' => '2010-02-04 21:05:36'
			),
			array(
				'id' => 21,
				'core' => 0,
				'name' => 'Logout',
				'url' => '/logout',
				'prefix' => '',
				'plugin' => 'management',
				'controller' => 'users',
				'action' => 'logout',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 0,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 15,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-02-04 21:05:49',
				'modified' => '2010-02-04 21:06:23'
			),
			array(
				'id' => 22,
				'core' => 0,
				'name' => 'Blog - Posts Seo',
				'url' => '/blog/:category/:id-:slug',
				'prefix' => '',
				'plugin' => 'blog',
				'controller' => 'posts',
				'action' => 'view',
				'values' => '',
				'pass' => 'id,slug',
				'rules' => '{\"id\":\"[0-9]+\"}',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 16,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-02-10 16:49:30',
				'modified' => '2010-02-18 18:49:20'
			),
			array(
				'id' => 23,
				'core' => 0,
				'name' => 'Contact - Contacts Seo',
				'url' => '/contact/:branch/:id-:slug',
				'prefix' => '',
				'plugin' => 'contact',
				'controller' => 'contacts',
				'action' => 'view',
				'values' => '',
				'pass' => 'id,slug',
				'rules' => '{\"id\":\"[0-9]+\"}',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 17,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-02-18 18:46:08',
				'modified' => '2010-02-18 18:48:40'
			),
			array(
				'id' => 24,
				'core' => 0,
				'name' => 'Contact - Branches Seo',
				'url' => '/contact/:id-:slug',
				'prefix' => '',
				'plugin' => 'contact',
				'controller' => 'branches',
				'action' => 'view',
				'values' => '',
				'pass' => 'id,slug',
				'rules' => '{\"id\":\"[0-9]+\"}',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 18,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-02-18 18:47:38',
				'modified' => '2010-02-18 18:48:30'
			),
			array(
				'id' => 25,
				'core' => 0,
				'name' => 'Shop - Categories',
				'url' => '/shop/categories/:id-:slug',
				'prefix' => '',
				'plugin' => 'shop',
				'controller' => 'shop_categories',
				'action' => 'index',
				'values' => '',
				'pass' => 'id,slug',
				'rules' => '{\"id\":\"[0-9]+\"}',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 19,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-05-04 19:52:11',
				'modified' => '2010-05-17 01:26:21'
			),
			array(
				'id' => 26,
				'core' => 0,
				'name' => 'Shop - Products',
				'url' => '/shop/:id-:slug',
				'prefix' => '',
				'plugin' => 'shop',
				'controller' => 'products',
				'action' => 'view',
				'values' => '',
				'pass' => 'id,slug',
				'rules' => '{\"id\":\"[0-9]+\"}',
				'force_backend' => 0,
				'force_frontend' => 1,
				'order_id' => 1,
				'ordering' => 20,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-05-05 04:30:03',
				'modified' => '2010-05-05 04:38:47'
			),
			array(
				'id' => 27,
				'core' => 0,
				'name' => 'Shop - Dashboard',
				'url' => '/shop',
				'prefix' => '',
				'plugin' => 'shop',
				'controller' => 'products',
				'action' => 'dashboard',
				'values' => '',
				'pass' => '',
				'rules' => '',
				'force_backend' => 0,
				'force_frontend' => 0,
				'order_id' => 1,
				'ordering' => 21,
				'theme_id' => 0,
				'active' => 1,
				'created' => '2010-05-05 04:47:21',
				'modified' => '2010-05-05 04:47:21'
			),
		),
		'ShortUrl' => array(
			array(
				'id' => 1,
				'url' => 'http://localhost/infinitas/management/users/activate/',
				'created' => '2010-05-15 14:24:05',
				'modified' => '2010-05-15 14:24:05'
			),
			array(
				'id' => 2,
				'url' => 'http://localhost/infinitas/management/users/activate/4bee85c7-47a0-47e4-a72a-0c746318cd70',
				'created' => '2010-05-15 14:30:15',
				'modified' => '2010-05-15 14:30:15'
			),
			array(
				'id' => 3,
				'url' => 'http://localhost/infinitas/management/users/activate/4bee85dc-d940-437b-9d8d-0c746318cd70',
				'created' => '2010-05-15 14:30:36',
				'modified' => '2010-05-15 14:30:36'
			),
			array(
				'id' => 4,
				'url' => 'http://localhost/infinitas/management/users/activate/4bee85f4-0d70-48be-aa9d-0c746318cd70',
				'created' => '2010-05-15 14:31:00',
				'modified' => '2010-05-15 14:31:00'
			),
			array(
				'id' => 5,
				'url' => 'http://localhost/infinitas/management/users/activate/4bee860e-a1ec-4958-93d3-0c746318cd70',
				'created' => '2010-05-15 14:31:26',
				'modified' => '2010-05-15 14:31:26'
			),
			array(
				'id' => 6,
				'url' => 'http://localhost/infinitas/management/users/activate/4bee8647-657c-44af-bc2e-0c746318cd70',
				'created' => '2010-05-15 14:32:23',
				'modified' => '2010-05-15 14:32:23'
			),
			array(
				'id' => 7,
				'url' => 'http://localhost/infinitas/management/users/activate/4bee8704-5f6c-4a49-b5d4-0c746318cd70',
				'created' => '2010-05-15 14:35:32',
				'modified' => '2010-05-15 14:35:32'
			),
		),
		'Theme' => array(
			array(
				'id' => 1,
				'name' => 'default',
				'description' => 'This is the default infinitas theme',
				'author' => 'Infinitas',
				'url' => '',
				'update_url' => '',
				'licence' => '',
				'active' => 0,
				'core' => 1,
				'created' => '2010-01-14 01:39:54',
				'modified' => '2010-01-14 01:39:57'
			),
			array(
				'id' => 2,
				'name' => 'terrafirma',
				'description' => '',
				'author' => '',
				'url' => '',
				'update_url' => '',
				'licence' => '',
				'active' => 0,
				'core' => 0,
				'created' => '0000-00-00 00:00:00',
				'modified' => '0000-00-00 00:00:00'
			),
			array(
				'id' => 3,
				'name' => 'aqueous',
				'description' => 'A blue 3 col layout',
				'author' => 'Six Shooter Media\r\n',
				'url' => '',
				'update_url' => '',
				'licence' => '',
				'active' => 0,
				'core' => 0,
				'created' => '0000-00-00 00:00:00',
				'modified' => '0000-00-00 00:00:00'
			),
			array(
				'id' => 4,
				'name' => 'aqueous_light',
				'description' => 'aqueous_light',
				'author' => '',
				'url' => '',
				'update_url' => '',
				'licence' => '',
				'active' => 0,
				'core' => 0,
				'created' => '0000-00-00 00:00:00',
				'modified' => '0000-00-00 00:00:00'
			),
			array(
				'id' => 5,
				'name' => 'rekordz',
				'description' => '<p>\r\n	&nbsp;</p>',
				'author' => '',
				'url' => '',
				'update_url' => '',
				'licence' => '',
				'active' => 1,
				'core' => 0,
				'created' => '2010-05-03 13:43:07',
				'modified' => '2010-05-19 13:45:53'
			),
		),
		'User' => array(
			array(
				'id' => 1,
				'username' => 'admin',
				'email' => 'admin@admin.com',
				'password' => 'b45e7cddbeafb9f619d93fd996c6a78c784e7fb5',
				'birthday' => '2010-02-04',
				'active' => 1,
				'group_id' => 1,
				'ip_address' => '127.0.0.1',
				'browser' => 'Mozilla 5.0',
				'operating_system' => 'Linux',
				'last_login' => '2010-09-13 11:14:53',
				'last_click' => '0000-00-00 00:00:00',
				'country' => 'Unknown',
				'city' => '',
				'is_mobile' => 0,
				'created' => '2010-02-04 16:54:48',
				'modified' => '2010-02-04 16:54:48',
				'facebook_id' => 0,
				'twitter_id' => 0
			),
		),
		),
	);
	
/**
 * Before migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function before($direction) {
		return true;
	}

/**
 * After migration callback
 *
 * @param string $direction, up or down direction of migration process
 * @return boolean Should process continue
 * @access public
 */
	public function after($direction) {
		return true;
	}
}
?>